### ISSUE TITLE
HELP? Too much noise on cc1101?

### ISSUE THREAD

**Issue by tablatronix** [NorthernMan54/rtl_433_ESP#100]
I know better than to ask for support in issues but I am at my wits end and have my entire workbench right now dedicated to this stupid project... lol

I am having nothing but issues with the C1101, I have 3 modules across esp32 various boards.
I get this all the time, where is this coming from? I sniff GD0 and there is nothing there, I see my accurite 5in1 data stream now and then, but this noise is always being reported ( I assume from miso interface? )

![Screenshot 2023-08-18 at 9 39 42 PM](https://github.com/NorthernMan54/rtl_433_ESP/assets/807787/70e1c04b-5e92-4770-91a9-0fa380774d64)

What could cause this, what am I doing wrong? Is there really this much noise around me on 433?

Is this what everyone deals with, is this normal. I can only receive and decode if I am very close to device.

Any debugging tips without an SDR ?  I hear some other devices on my scanner but nothing that should be this noise

**Comment by tablatronix** [comment]
I had to DDISABLERSSITHRESHOLD to receive, I think it doesn't work at all in my environment, I think maybe there is a single high power pulse near me that is causing issues with rssi tracking maybe, not sure.

**Comment by tablatronix** [comment]
Replaced antenna with a tuned one, these "433" ones are terrible, turned off autorssithreshhold

Getting ~100% now at 100ft , I will try to figure out the rssi averaging and noise later when I have time

![Screenshot 2023-08-21 at 7 45 36 AM](https://github.com/NorthernMan54/rtl_433_ESP/assets/807787/d765f188-2efc-4cd1-9e5e-2033a2ede627)

**Comment by NorthernMan54** [comment]
That is very good results,  can you share a link to the antenna ?

**Comment by tablatronix** [comment]
I made a 1/4 whip, need the db to get above noise floor. Still no idea why its so high, could be the strong 433 beacon I hear, and also another weather station slight farther than mine.. Could be all these cc1101 are fake or rejects ( i hear there is also some silicon bugs in these and workarounds) I have not checked rtl_433 to see the specifics or if they are handled just saw some notes on some forums.
![image](https://github.com/NorthernMan54/rtl_433_ESP/assets/807787/59c8cdab-cc3a-4625-9076-4efeae8e3120)

**Comment by jasiek** [comment]
Can you share which CC1101 module you were using?

**Comment by tablatronix** [comment]
I used both these
![IMG_2100](https://github.com/NorthernMan54/rtl_433_ESP/assets/807787/32882cd5-cf66-4f2f-aaba-c37a57ea23e6)

i gave up and moved to a lora32 sx1278 its a much more complex chip
