### ISSUE TITLE
Simple HW question

### ISSUE THREAD

**Issue by Crsarmv7l** [NorthernMan54/rtl_433_ESP#101]
I am not seeing any difference between the paxcounter and the disaster radio for the ttgo board aside from the fw.

 Just wanted to ensure that was the case.
![Screenshot 2023-09-14 10 01 49 AM](https://github.com/NorthernMan54/rtl_433_ESP/assets/85343771/e10620d7-3c61-456a-a348-a3d6acc180db)

**Comment by NorthernMan54** [comment]
The difference is the factory installed 'default firmware'

The SX1278 and SX1276 Module is supported

**Comment by Crsarmv7l** [comment]
> The difference is the factory installed 'default firmware'
> 
> The SX1278 and SX1276 Module is supported

Awesome, thanks. That is what I thought. Last question: how deeply integrated is openMQTTGateway?

I would like to use this as basically a standalone rtl_433 without needing a computer (maybe logging to a file like rtl_433 with json if that is supported)

**Comment by NorthernMan54** [comment]
I run it within OpenMQTTGateway as it provides a framework for the library to run within, including WiFi and MQTT integration.

Logging to a file on a ESP32 is problematic due to the usage a flash memory on the device.  I send the via MQTT, then listen to the topic to utilize the data.

**Comment by Crsarmv7l** [comment]
Cool thanks.
