### ISSUE TITLE
915Mhz version

### ISSUE THREAD

**Issue by Drummondh** [NorthernMan54/rtl_433_ESP#103]
### Current Situation

I have RTL_433 running on a linux box with a SDR and thought this might be a better way to do it but I am also looking to look at 915Mhz devices.  In RTL_433 you use "rtl_433 -f 914900000 -s 250k" when you run it.  
Is there any way to make that change in this?  
I have ordered the LILYGO LoRa32 in both 433 and 915 to give it a try.

Thanks!

### Proposed Change

Add basic functionality similar to starting rtl_433 with "rtl_433 -f 914900000 -s 250k".

**Comment by NorthernMan54** [comment]
If you look into the examples, I included the config from my testing @ 915 Mhz - https://github.com/NorthernMan54/rtl_433_ESP/blob/0b9b378bd390c0dc53751c34816b1f5d5cbb14c1/example/OOK_Receiver/platformio.ini#L116
