### ISSUE TITLE
Capability to interrupt decoder during successful partial decode.

### ISSUE THREAD

**Issue by bgmcode** [NorthernMan54/rtl_433_ESP#109]
### Current Situation

The Reolink doorbell signal lasts about 4 seconds, with the doorbell code payload being repeated over and over. As I have it currently implemented, my doorbell won't ring until those 4 seconds are up.

How would you recommend updating my fork to stop decoding once the doorbell code is successfully read? I'm having a hard time understanding how your code works. Thanks again!

### Proposed Change

Capability to interrupt decoder during successful partial decode.

**Comment by NorthernMan54** [comment]
I'm not sure if this is feasible, but the start and end of signal is controlled by this function https://github.com/NorthernMan54/rtl_433_ESP/blob/3fea1cf678212ea5ef70e38f625bc8505f73bb28/src/rtl_433_ESP.cpp#L531

And the start and end of signal is currently detected by the RSSI level.
