### ISSUE TITLE
Is FSK modulation supported with CC1101?

### ISSUE THREAD

**Issue by habub** [NorthernMan54/rtl_433_ESP#118]
### Current Situation

I get this type of error for devices I suspected transmit FSK:
`rtl_433_ESP(6): Ignored Signal length: 81000, Time since last bit length: 5072, Gap length: 4385, Signal RSSI: -45, Current RSSI: -80, pulses: 0, noise count: 1`
Not sure it's related to FSK, but OOK devices work well.
It looks like FSK demod is supported in the code base, but then there's this:
```
#ifdef RF_CC1101
  int state = radio.begin();
#else
  int state = radio.beginFSK();
#endif
  RADIOLIB_STATE(state, "radio.begin()");
```
what's missing to support FSK with CC1101? Is it just registers based on the FSK Example?

### Logs

```markdown
NA
```

### Configuration

```json
NA
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
The CC1101 is supported with FSK.  That bit of code is due the differences with RadioLib with the two different transceiver modules
