### ISSUE TITLE
Disable Arduino Log library?

### ISSUE THREAD

**Issue by habub** [NorthernMan54/rtl_433_ESP#129]
### Current Situation

In the Arduino-Log library [documentation](https://github.com/1technophile/Arduino-Log?tab=readme-ov-file#disable-library) it is shown how to disable the logging and significantly reduce the project size.
I tried adding `#define DISABLE_LOGGING` in both logging files (libdeps/ArduinoLog.h and /include/logger.h) but it had no impact.

Any ideas?

### Logs

```markdown
NA
```

### Configuration

```json
NA
```

### Environment

NA

### Process Supervisor

not applicable

### Additional Context

.../libdeps/arduinolog/ArduinoLog.h:
```
// *************************************************************************
//  Uncomment line below to fully disable logging, and reduce project size
// ************************************************************************
//#define DISABLE_LOGGING
```

**Comment by NorthernMan54** [comment]
How do you do an out of office for GitHub issues - I’m away till mid March and can look at this then

I expect my flavor of arduino log to be broken or something
