### ISSUE TITLE
What would it take to have the code run on an unexpected maker esp32 feather s3?

### ISSUE THREAD

**Issue by DotCom2001** [NorthernMan54/rtl_433_ESP#133]
### Current Situation

I am a beginner in embedded technology. I am trying to use this code on another type of esp32 board (Unexpected Maker Esp32-S3 Feather Board) to capture TPMS signals using a CC1101. I tried to thinker with the code to have the board be supported. However, I seem to create more issues than I solve.  

I am not searching to use MQTTGateway.

I essentially am in search of guidance to start this process from scratch. 

### Logs

```markdown
Nothing to report
```

### Configuration

```json
Nothing to report
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by avicarmeli** [comment]
You can try [that] (https://github.com/avicarmeli/TPMS-SDR/tree/main) should work with your board.
