### ISSUE TITLE
[43]  Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor 

### ISSUE THREAD

**Issue by kyuzumaki** [NorthernMan54/rtl_433_ESP#135]
### Current Situation
Edit: Ok I'm wrong it's listed under a different number 
Registering protocol [54] "Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor"

Not sure why it is not working. Any tips on how to debug this? I have a working RTL-SDR so am able to see when a packet comes in from the sensor. Its about 20m away. Has direct LOS through a window.

Previous message:

I've been using rtl_433 to read an oil sensor. After setting up OpenMQTT gateway to try to replace the RTL-SDR system i'm using. I've discovered it dosent seem to be picking up my tank sensor.
The offical rtl_433 library has this decoder 
[43]  Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor
Is there any way to get this one working?
I would be happy having it ignore every other protocol if that frees up enough resource on the esp to decode just that signal.

Currently setup is a Lilygo_433 with OpenMQTT running and connected to home assistant. Ive let it run for a good while and have not seen any new sensors show up in Home assistant.

### Proposed Change

Add 
[43]  Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor
from trl_433 library

**Comment by DigiH** [comment]
> Edit: Ok I'm wrong it's listed under a different number
> Registering protocol [54] "Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor"

When you found the existing decoder being actually included, did you see that it is under the **FSK** section, so the **FSK** modulation will need to be set, as described in the Compile Definition Options section

https://github.com/NorthernMan54/rtl_433_ESP?tab=readme-ov-file#compile-definition-options

Let us know how you get on.

**Comment by kyuzumaki** [comment]
Thank you! I noticed it was in a different section but failed to recognise my mistake. Working perfectly now
