### ISSUE TITLE
ESP32 RTL_433 sensors simulator

### ISSUE THREAD

**Issue by avicarmeli** [NorthernMan54/rtl_433_ESP#146]
### Current Situation

Lately I needed to replicate one off the RTL_433 devices transmissions (Renault TPMS) for development prepose.
I cam up with that [code](https://github.com/avicarmeli/ESP32_TPMS_Sim).

### Proposed Change

I am having thoughts about writing a generic code which would make it possible to simulate all of rtl_433 recognized devices.
I am writing here to ask you for ideas and lesson learned as well as your thoughts about the necessity of such code.

**Comment by NorthernMan54** [comment]
I am writing here to ask you for ideas and lesson learned as well as your thoughts about the necessity of such code.

I found that using the real devices for testing is best, as there maybe features or suttlies in the signal from the original device that may be overlooked with test code.  I had tried to do the original effort around FSK signal reception using a simulated device, and got about 80% of the work completed, but required an actual device to finalize the effort.
