### ISSUE TITLE
arduino LoRa library

### ISSUE THREAD

**Issue by biospank** [NorthernMan54/rtl_433_ESP#148]
### Current Situation

I'm using this library with Lilygo LoRa32 V2.1_1.6 (433) board and everything works fine.
When I add [arduino LoRa](https://github.com/sandeepmistry/arduino-LoRa) library to relay the incoming rtl_433_ESP message to remote LoRa module it stops to work.
I think it's something related to the initialization and default configuration of these two libraries

**rtl_433_ESP** initialization code:
`rf.initReceiver(RF_MODULE_RECEIVER_GPIO, 433.92);`
**arduino LoRa** initialization code:
`digitalPinToInterrupt(LORA_IRQ);
  LoRa.setPins(LORA_CS, LORA_RST, LORA_IRQ);`

I there any way to use both library at the same time avoiding conflict?

Any help would be appreciated.

### Logs

```markdown
no logs
```

### Configuration

```json
no conf
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
The rtl_433 library is using the Lora chip to receive 433 MHz messages so using the Lora chip to send Lora messages at the same time is not feasible.
