### ISSUE TITLE
link to helltech in readme  is redirected to the V3 revision : questions about the features supported by this board?

### ISSUE THREAD

**Issue by ouinouin** [NorthernMan54/rtl_433_ESP#152]
### Current Situation

while reading the doc i came to the conclusion that the 1262 chip was not the most versatile choice since not supporting FSK to my understanding.   the link :  [Heltec SX127X](https://heltec.org/project/wifi-lora-32/) is pointing to the V3 revision which has a sx1262 , so i dont know if its the best choice, and i dont know if you were testing on the V2 or V3 harware, maybe a table with the hardware, versions and capabilities should help to pick the good choice. (additional question, i couldnt yet understant if the OOK and FSK modes are supported at the same time ? ).

### Logs

```markdown
na
```

### Configuration

```json
na
```

### Environment

- OS: linux
- Software: rtl_433_esp
- Node: 
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Tks for the feedback in regards to the broken link.  I have updated the README with a corrected link and added more wording in regards to the required chipset.

Tks
