### ISSUE TITLE
How to reduce the library size?

### ISSUE THREAD

**Issue by garudaonekh** [NorthernMan54/rtl_433_ESP#21]
Hi,
I am using this with my existing project which is already quite big. How to reduce this library size?
Actually, I just need to use 1 weather station and 3 soil moisture sensor so 2 types of devices only.

Thanks;

**Comment by NorthernMan54** [comment]
I setup a define in the codebase called mydevices that implements just my personal devices, if you look for that in the codebase, you can see how to reduce it.
