### ISSUE TITLE
Add that project to Platform IO registry 

### ISSUE THREAD

**Issue by joroMaser** [NorthernMan54/rtl_433_ESP#32]
Please add that project to Platform IO registry so we can easily install to esp32

**Comment by NorthernMan54** [comment]
Personally I use the project from within OpenMQTTGateway, and use it with platformio to do my builds etc.

**Comment by joroMaser** [comment]
But most of time I just want to use receiver to print RF data without any use of OpenMQTTGateway like
https://github.com/NorthernMan54/rtl_433_ESP/blob/master/example/OOK_Receiver/OOK_Receiver.ino

So I offer to add that project stand-alone to PlatformIO registry

**Comment by KiCADHugo** [comment]
OpenMQTTGateway is too large for me, and i don't understand configure it. so how can i use this library with platformio separately?
I have a LilyGo T3_v1.6.1 433 MHz.

**Comment by NorthernMan54** [comment]
The folder example/OOK_Receiver is a standalone example
