### ISSUE TITLE
Support for Fine Offset WH25

### ISSUE THREAD

**Issue by melyux** [NorthernMan54/rtl_433_ESP#49]
I know, I know, it's in RTL_433 but [it's FSK](https://github.com/merbanan/rtl_433/blob/b605a3d2a7df02eae5e3405469e79810dfa0b7a3/src/devices/fineoffset.c#L1022). Looks like the FSK development here has stalled, but do you have a guide on how I can try to get it ported from RTL_433 and implemented myself? I have physical access to the device

Full name on RTL_433: "Fine Offset Electronics, WH25, WH32B, WH24, WH65B, HP1000, Misol WS2320 Temperature/Humidity/Pressure Sensor"

**Comment by NorthernMan54** [comment]
Unfortunately I don't have a guide available for how to add FSK support.

The challenge with FSK, is that with the receivers we are supporting for this project they are doing signal demodulation within the chip.  So first the receiver chip needs to be configured for FSK mode and confirmed that it is able to receive the signal.  Then you could look at adding the decoder to the code base, and other changes for FSK.

FYI -  with FSK enabled, support for receiving OOK signals would no longer available as the receiver chip can only support a single mode of demodulation at a time.
