### ISSUE TITLE
OOK-Sample creates unknown Files in Win-User Temp Folder

### ISSUE THREAD

**Issue by Jo59Devs** [NorthernMan54/rtl_433_ESP#56]
Why does the software create files in the Windows user's Temp folder?
In my case:
tmpm6ubhpzr
Used Compiler: VisualStudioCode

**Comment by NorthernMan54** [comment]
No sure what I can contribute here, as the software package runs on a ESP32 and not Windows.  If the compiler is putting files into Temp, that is likely a compiler configuration issue.

PS I'm a MacOS User and don't the same issue when compiling
