### ISSUE TITLE
How to use in Arduino IDE 1.8.19 ?

### ISSUE THREAD

**Issue by beta-tester** [NorthernMan54/rtl_433_ESP#67]
hi, i tried to use this library in Arduino IDE 1.8.19, but i don't know how to get it work.
i tried to git clone into `~/Arduino/libraries/rtl_433_ESP` folder and i tried to add the "rtl_433_ESP-master.zip" to the Arduino IDE Library Manager.
both methods didn't work.

**Comment by beta-tester** [comment]
PS.: i also tried to install VCode and following the build instructions:
https://github.com/NorthernMan54/rtl_433_ESP/blob/master/example/OOK_Receiver/README.md
the first two steps are ok, but i fail to follow step `3 - Select and build either the esp32_cc1101, esp32_heltec or esp32doitv1_r01 environment`...
where/how to select `esp32_heltec` and where to build

**Comment by NorthernMan54** [comment]
Easiest is to just use OpenMQTTGateway

The VSCODE/Platformio environment selector is at the bottom of the page

![Screen Shot 2023-03-21 at 9 56 56 AM](https://user-images.githubusercontent.com/19808920/226628915-ab024e3f-e786-4067-86b0-c624d6f45ada.png)

**Comment by beta-tester** [comment]
thank you.
i installed Visual Studio Code, but i forgot to install the PlatformIO extension in Visual Studio Code.
with PlatformIO Extension i get the project to build and run. thank you.

PS.: unfortunately it mix up with Espressif-IDE Extension icons for Build/Upload and Monitor.
![VCODE_ESPRESSIF_PLATFORMIO](https://user-images.githubusercontent.com/4750719/226635101-57a80cfe-eaf3-4fb8-845f-d8daa3ac04f4.png)

**Comment by NorthernMan54** [comment]
Good luck

**Comment by beta-tester** [comment]
do you know if that is normal,
that i now have two different sets of icons to build/flash/monitor one set for Espressif-IDE and one for PlatformIO is that nomal?

**Comment by NorthernMan54** [comment]
Sorry I'm not an expert with PlatformIO, but in my setup I do not use Espressif-IDE extension

**Comment by beta-tester** [comment]
ok, thank you for your help and the library...
i will ask the Espressif-IDE or PlatformIO extension maintainer for the issue with the icons.

**Comment by uriva9w** [comment]
Dear Beta tester, could you please share your library in a zip format. I am not a literate with MS Studio Platform IO, i just want to test NorthernMan54's effort to read my water meter. Thx in advance
