### ISSUE TITLE
How to add missing devices to decode?

### ISSUE THREAD

**Issue by beta-tester** [NorthernMan54/rtl_433_ESP#68]
hi,
i am using the example `OOK_Receiver.ino` to see what i get from the sensors around me.
i have two sensors that wont get decoded.

they only produce a RAW dump.

with my RTL_SDR + RTL_433 on my Raspberry Pi it apears as an "Ambientweather-F007TH"
the device is located in:
https://github.com/merbanan/rtl_433/blob/master/src/devices/ambient_weather.c

how can i include this device from `rtl_433` to `rtl_433_ESP` ?

just copying all the devices from `~/git/merbanan/rtl_433/src/devices` to `~/git/NorthernMan54/rtl_433_ESP/src/rtl_433/devices` and recompile does not do anything.

i don't know how the devices are linked together

**Comment by CazYokoyama** [comment]
add your device to rtl_433_devices.h. The macro, DEVICES lists the devices which can be decoded. Don't forget to increase NUMOFDEVICES.

Even you add your device, it still not be decoded, your device does not satisfy the requirements which are
433MHz
OOK(On-Off-Keying), not FSK(Frequency shift keying).

**Comment by beta-tester** [comment]
by adding to https://github.com/NorthernMan54/rtl_433_ESP/blob/master/src/decoder.cpp#L168
```c

memcpy(&cfg->devices[104], &ambient_weather, sizeof(r_device));
```
and adding/changing https://github.com/NorthernMan54/rtl_433_ESP/blob/master/include/rtl_433_devices.h#L116
```c
  DECL(ambient_weather)                                                              \
  /* Add new decoders here. */
#define NUMOFDEVICES 105
```

and commenting out all three `decoder_logf_bitrow` (because in the meantime the error handling changed in the rtl_433 master)
from https://github.com/merbanan/rtl_433/blob/master/src/devices/ambient_weather.c#L59

it **DOES** decode the sensor!

**Comment by CazYokoyama** [comment]
You are welcome. Please close the cause.
