### ISSUE TITLE
please add `OOK_PULSE_MANCHESTER_ZEROBIT` to `update_rtl_433_devices.sh`

### ISSUE THREAD

**Issue by beta-tester** [NorthernMan54/rtl_433_ESP#70]
hi, please add `OOK_PULSE_MANCHESTER_ZEROBIT` to `update_rtl_433_devices.sh`.
e.g.:
```bash
#! /bin/sh

export MODULATION="OOK_PULSE_PWM|OOK_PULSE_PPM|OOK_PULSE_MANCHESTER_ZEROBIT"

```

in the README.md is written that `OOK_PULSE_MANCHESTER_ZEROBIT` is working, but none of the devices that supporst `OOK_PULSE_MANCHESTER_ZEROBIT` modulation are included to the devices folder.

**Comment by NorthernMan54** [comment]
Pls watch this branch https://github.com/NorthernMan54/rtl_433_ESP/tree/rtl_433-22.11

**Comment by beta-tester** [comment]
thanks, that branch helps me alot
