### ISSUE TITLE
Support for Emax W6

### ISSUE THREAD

**Issue by qupen** [NorthernMan54/rtl_433_ESP#77]
Hi! First of all, thanks for all this work you are doing.
And i just want to ask if it is possible do enable the emax device from the rtl_443 project to rtl_443_ESP?
You can find the link here:
https://github.com/merbanan/rtl_433/blob/master/src/devices/emax.c

Thanks for the ennoblement of my data hording needs.

**Comment by NorthernMan54** [comment]
It uses FSK modulation, which is something I have never been able to get working correctly.  So support is a maybe with the next release.  Also challenging is that I do not have to the device, so I won't be able to test if it works.

https://github.com/NorthernMan54/rtl_433_ESP/blob/09c4a5063494f603877a38b866c8534bd21817d0/src/rtl_433/devices/emax.c#L273
