### ISSUE TITLE
Any chance the SRX882/STX882 will be supported in this project?

### ISSUE THREAD

**Issue by thestraycat** [NorthernMan54/rtl_433_ESP#79]
Great looking project! Congrats. Just wanted to know whether the hardware i have assembled will ever be likely supported or not so i can run it! :)

**Comment by NorthernMan54** [comment]
The code base leverages signal detection logic within the transceiver module to determine start and end of signal, and the srx882 does not have this capability.  So unfortunately it can’t be supported.
