### ISSUE TITLE
868 Mhz Ambient Weather Sensors

### ISSUE THREAD

**Issue by doswiss** [NorthernMan54/rtl_433_ESP#80]
Will it also work on 868Mhz when i choose the "ESP32 868MHZ"? On my linux and with a SDRPlay i was able to get the sensor informations.

https://github.com/merbanan/rtl_433/blob/master/src/devices/ambientweather_wh31e.c

Regards,
doswiss

**Comment by NorthernMan54** [comment]
The ability to receive on 868Mhz depends on what your chip set/receiver module supports.  Technically it should.

**Comment by doswiss** [comment]
okay, thanks for the fast answer. if i use one of the LILYGO with 443 or 868 included, i still need a CC1101? Or can i just use the onboard transmiter?

**Comment by NorthernMan54** [comment]
You can use the onboard chipset ( That is the picture in the readme )

**Comment by NorthernMan54** [comment]
At this point I would say maybe, the latest release included all the FSK device decoders, but the receiver chipset needs more tuning to be able to receive signals.   If we are successful in determining the proper tuning, then it is likely to work.

**Comment by NorthernMan54** [comment]
Please update and try again with the latest release.  I completed testing and tuning with FSK based devices.

**Comment by doswiss** [comment]
Hello @NorthernMan54 

Thanks for your work :) I usually installed the version from the OpenMQTT Web Installer. Now i build some knowhow to compile it with Visual Studio and platformio. I'am not sure how the file must look:

 

> ;lilygo-rtl_433
> [env:lilygo-rtl_433]
> platform = ${com.esp32_platform}
> board = ttgo-lora32-v21
> ; ~/.platformio/packages/framework-arduinoespressif32/variants/.../pins_arduino.h
> board_build.partitions = min_spiffs.csv
> lib_deps =
>   ${com-esp.lib_deps}
>   ${libraries.wifimanager32}
>   ${libraries.ssd1306}
>   ${libraries.rtl_433_ESP}
> build_flags =
>   ${com-esp.build_flags}
> ; *** OpenMQTTGateway Config ***
>   ;'-UZmqttDiscovery'          ; disables MQTT Discovery
>   '-DvalueAsATopic=true'    ; MQTT topic includes model and device
> ;  '-DGateway_Name="OpenMQTTGateway_lilygo_rtl_433_ESP"'
> ; *** OpenMQTTGateway Modules ***
>   '-DZgatewayRTL_433="rtl_433"'
>   '-DZradioSX127x="SX127x"'
> ; *** ssd1306 Display Options ***
>   '-DZdisplaySSD1306="LilyGo_SSD1306"'
>   '-OOK_MODULATION=false'
> ;  '-DLOG_TO_LCD=true'         ; Enable log to LCD
> ;  '-DJSON_TO_LCD=true'
> ;  '-DLOG_LEVEL_LCD=LOG_LEVEL_NOTICE'
> ;  '-DDISPLAY_IDLE_LOGO=false'
> ;  '-DDISPLAY_METRIC=false'
>   '-DCC1101_FREQUENCY=868.35'
>   '-DESPWifiManualSetup=true'
>   '-Dwifi_ssid="*******"'
>   '-Dwifi_password="******"'
>   '-DMQTT_SERVER="*****"'
>   '-DMQTT_USER="******"'
>   '-DMQTT_PASS="*******"'
>   '-DMQTT_PORT="1883"'

custom_description = For ESP32, Gateway using RTL_433_ESP and RadioLib
custom_hardware = ESP32 LILYGO LoRa32 V2.1`

When i add the the propertie " '-OOK_MODULATION=false" it fails when i want to compile:

> Building in release mode
> Compiling .pio\build\lilygo-rtl_433\src\main.ino.cpp.o
> xtensa-esp32-elf-g++: error: unrecognized command line option '-R'
> Compiling .pio\build\lilygo-rtl_433\src\zzHTTPUpdate.cpp.o
> xtensa-esp32-elf-g++: error: unrecognized command line option '-R'
> Compiling .pio\build\lilygo-rtl_433\libaa4\PubSubClient\PubSubClient.cpp.o
> xtensa-esp32-elf-g++: error: unrecognized command line option '-R'
> Compiling .pio\build\lilygo-rtl_433\lib043\ArduinoLog\ArduinoLog.cpp.o

Thanks :)

**Comment by doswiss** [comment]
I made a typo, like that it's working:

  '-DOOK_MODULATION=false'

And i already get information from my sensors:

> {"model":"AmbientWeather-WH31E","id":249,"channel":5,"battery_ok":1,"temperature_C":19,"humidity":51,"data":"ef00000000","mic":"CRC","protocol":"Ambient Weather WH31E Thermo-Hygrometer Sensor, EcoWitt WH40 rain gauge","rssi":-66,"duration":52000}

**Comment by NorthernMan54** [comment]
That’s great to hear
