### ISSUE TITLE
Support for SX1262 chip (board heltec_wifi_lora_32_V3 )

### ISSUE THREAD

**Issue by max-fedorov** [NorthernMan54/rtl_433_ESP#82]
Hello! Many thanks for you great library!

Want to ask add support for new Heltec modules WiFi LoRa 32 (V3) with chip  SX1262 and ESP32S3.
Main problem with that V3 board there is an chip ESP32S3 and updated pinout - doesn't have pin DIO2 on board.

Some usefull links:
https://heltec.org/project/wifi-lora-32-v3/
https://docs.platformio.org/en/latest/boards/espressif32/heltec_wifi_lora_32_V3.html
https://resource.heltec.cn/download/WiFi_LoRa32_V3/HTIT-WB32LA(F)_V3_Schematic_Diagram.pdf
https://github.com/jgromes/RadioLib/blob/master/examples/SX126x/SX126x_FSK_Modem/SX126x_FSK_Modem.ino

**Comment by NorthernMan54** [comment]
The main problem is deeper than that, rtl_433_ESP uses `OOK Continuous Mode` of the sx127x chipset ( See section 4.2.12 of the data sheet ), and this mode does not exist in the SX126x chipset. The SX126X datasheet mentions a continuous mode, but it is not the same.

So the issue is more than missing pins, but missing feature.

**Comment by sheilbronn** [comment]
Thx for the quick and fast explanation!

May I suggest marking it explicitly in the docs that V3 is not (yet) supported?! This might help avoiding others to make the same buying mistake as I did...

**Comment by NorthernMan54** [comment]
You can still use the board to receive Bluetooth signals with OMG and the BLE build

**Comment by sheilbronn** [comment]
> 
And how can I use the OLED? Thx

**Comment by NorthernMan54** [comment]
With OMG and the Blue Tooth build, it will display bluetooth signals
