### ISSUE TITLE
Board Support request

### ISSUE THREAD

**Issue by detectingdragon77** [NorthernMan54/rtl_433_ESP#84]
I have this board: https://heltec.org/product/wireless-stick-lite-v3/
It uses an esp32s3. Would it be possible to add support for this board in the future?

**Comment by sheilbronn** [comment]
Related to https://github.com/1technophile/OpenMQTTGateway/issues/1619 ?!

**Comment by NorthernMan54** [comment]
@detectingdragon77 Tks for the link to the product.  The particular model uses the SX1262 transceiver chipset which is not supported.

**Comment by detectingdragon77** [comment]
> @detectingdragon77 Tks for the link to the product. The particular model uses the SX1262 transceiver chipset which is not supported.

Ok
