### ISSUE TITLE
Support for LilyGO TTGO T3 LoRa32 V1.6.1 ESP32 in the 868 Mhz version 

### ISSUE THREAD

**Issue by heribertmsb** [NorthernMan54/rtl_433_ESP#90]
Dear all,
is it possible to use the project also in 868 MHz version.
Which would be the required changes?

**Comment by NorthernMan54** [comment]
It should work properly with the appropriate compiler directives and frequency set.  I don't have your board so I can't confirm, but I was successful in testing with a similar Heltec board at 915Mhz

**Comment by doswiss** [comment]
i can confirm it will work. I use the same setup.
