### ISSUE TITLE
Acurite 00515 - freezer sensor can not receive information

### ISSUE THREAD

**Issue by rdaguerre** [NorthernMan54/rtl_433_ESP#98]
Hi, i cant receive data from freezer sensor. The refrigerador sensor work very good

N: Send on /RTL_433toMQTT/Acurite-515/AR/165 msg {"model":"Acurite-515","id":165,"channel":"AR","battery_ok":1,"temperature_C":4.72222,"mic":"CHECKSUM","protocol":"Acurite 592TXR Temp/Humidity, 592TX Temp, 5n1 Weather Station, 6045 Lightning, 899 Rain, 3N1, Atlas","rssi":-99,"duration":146000}

Thanks

**Comment by NorthernMan54** [comment]
Look at the RSSI value, it is very low from your refrigerator.   So I'm thinking that you can't receive from the freezer due to the low signal value.

Try moving the ESP32 closer to the freezer and make sure that the antenna is vertical.
